from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum


class LocationSchema(BaseModel):
    """Location information"""
    lat: float = Field(..., ge=-90, le=90, description="Latitude")
    lon: float = Field(..., ge=-180, le=180, description="Longitude")
    ward: str = Field(..., description="Ward name or identifier")
    area: Optional[str] = Field(None, description="Area/neighborhood name")


class HospitalEventSchema(BaseModel):
    """Hospital event data"""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    location: LocationSchema
    hospital_id: str
    hospital_name: str
    symptoms: List[str] = Field(..., description="List of reported symptoms")
    diagnosis: Optional[str] = None
    patient_count: int = Field(1, ge=1)
    severity: str = Field("mild", description="mild, moderate, severe")
    age_group: Optional[str] = Field(None, description="Age group of patients")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)


class SocialPostSchema(BaseModel):
    """Social media post data"""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    location: LocationSchema
    platform: str = Field(..., description="twitter, facebook, reddit, etc.")
    post_id: str
    text: str
    keywords: List[str] = Field(default_factory=list, description="Extracted symptom keywords")
    sentiment: Optional[float] = Field(None, ge=-1, le=1)
    engagement: Optional[int] = Field(0, ge=0)
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)


class EnvironmentDataSchema(BaseModel):
    """Environmental data"""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    location: LocationSchema
    temperature: Optional[float] = None
    humidity: Optional[float] = Field(None, ge=0, le=100)
    rainfall: Optional[float] = Field(None, ge=0)
    mosquito_index: Optional[float] = Field(None, ge=0, le=10)
    air_quality_index: Optional[float] = Field(None, ge=0)
    water_quality: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)


class DailyAggregateSchema(BaseModel):
    """Daily aggregated metrics per location"""
    date: datetime
    location: LocationSchema
    symptom_counts: Dict[str, int] = Field(default_factory=dict)
    social_keyword_counts: Dict[str, int] = Field(default_factory=dict)
    total_hospital_events: int = 0
    total_social_mentions: int = 0
    environmental_risk_score: float = 0.0
    rolling_mean_7d: Optional[float] = None
    rolling_std_7d: Optional[float] = None
    z_score: Optional[float] = None
    changepoint_detected: bool = False
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)


class ModelScores(BaseModel):
    """ML model anomaly scores"""
    z_score: Optional[float] = None
    cusum: Optional[float] = None
    ewma: Optional[float] = None
    lstm_autoencoder: Optional[float] = None
    isolation_forest: Optional[float] = None
    prophet_residual: Optional[float] = None


class AnomalyResultSchema(BaseModel):
    """Anomaly detection results"""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    location: LocationSchema
    anomaly_score: float = Field(..., ge=0, le=1, description="Unified anomaly score (0-1)")
    confidence: float = Field(..., ge=0, le=1)
    model_scores: ModelScores
    is_anomaly: bool = False
    severity: str = Field("low", description="low, medium, high, critical")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)


class EvidenceSchema(BaseModel):
    """Evidence supporting an alert"""
    hospital: Dict[str, Any] = Field(default_factory=dict)
    social: Dict[str, Any] = Field(default_factory=dict)
    environment: Dict[str, Any] = Field(default_factory=dict)
    model_scores: Dict[str, Any] = Field(default_factory=dict)


class RecommendedAction(BaseModel):
    """Recommended action for outbreak response"""
    category: str = Field(..., description="medicine, equipment, staffing, preparedness")
    action: str
    priority: str = Field("medium", description="low, medium, high, critical")
    target: str = Field(..., description="hospital, pharmacy, clinic, public")
    details: Optional[str] = None


class AlertSchema(BaseModel):
    """Alert generated by the system"""
    alert_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    location: LocationSchema
    confidence: float = Field(..., ge=0, le=1)
    anomaly_score: float = Field(..., ge=0, le=1)
    severity: str = Field("medium", description="low, medium, high, critical")
    evidence: EvidenceSchema
    recommended_actions: List[RecommendedAction] = Field(default_factory=list)
    status: str = Field("active", description="active, acknowledged, resolved")
    notified: bool = False
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)


class AlertResponse(BaseModel):
    """API response for alert queries"""
    alerts: List[AlertSchema]
    total: int
    page: int = 1
    page_size: int = 50
